#!/usr/bin/env bash

issue=$1
mr=$2
comment=$3
tmpdir="$(mktemp -d)"
curdir=$(pwd)
range=$(git merge-base --fork-point master $branch)..$branch
curbranch=$(git rev-parse --abbrev-ref HEAD)
sit=$(which sit)

if [ -z ${issue} ]; then
        echo "Usage: apply-merge-request <issue> <mr> [comment]"
        exit 1
fi

if [ -z ${mr} ]; then
        echo "Usage: apply-merge-request <issue> <mr> [comment]"
        exit 1
fi

if [ -z ${sit} ]; then
        echo "sit not found"
        exit 1
fi

repo=$(${sit} path)

git checkout -b review-${issue}-${mr} || exit 2

git am $(ls ${repo}/issues/${issue}/${mr}/git/*.patch) || exit 2
